services:
  - type: web
    name: ma-caisse-enregistreuse
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python lancer_caisse.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
